### ISSUE TITLE
Add possibility to add the top donator

### ISSUE THREAD

**Issue by Intrer** [littlepriceonu/Pls-Donate-Self-Bot#1]
Being able to see on the board who donated the most gives an incentive for people to donate a lot; they want to see their name on the board. Thus it would be beneficial if the script could automatically update this data onto the board.

**Comment by littlepriceonu** [comment]
Ill add this to the todo list

**Comment by littlepriceonu** [comment]
will be added in V2 (whenever I actually finish it lmao)
