### ISSUE TITLE
help

### ISSUE THREAD

**Issue by flamedev0** [littlepriceonu/Pls-Donate-Self-Bot#4]
whatever I do, my booth text is always getting tagged

**Comment by flamedev0** [comment]
using the auto goal update

**Comment by littlepriceonu** [comment]
Just a issue with roblox tagging out numbers, the best (and only way) to fix this is to turn off auto goal (_G.autoUpdateGoal = false) and set the _G.goal manually to something like "5K!" or sum like that.
